### ISSUE TITLE
Unexpected code

### ISSUE THREAD

**Issue by andreynovikov** [mapsforge/mapsforge-mapcreator#10]
Is typo in [this line](https://github.com/mapsforge/mapsforge-mapcreator/blob/master/landextraction.py#L131) intentional?

**Comment by devemux86** [comment]
IIRC yes, since simplification should be left for map-writer and input data being unmodified.

@ludwigb ?

**Comment by applantation** [comment]
I guess what happened here was that I was playing with various options and
somehow an attempt to hard-code this was left behind. The line should go,
the code works correctly in the sense that the command-line option is
passed all the way to this routine.

I cannot remember what real impact the land-simplification had here, but
maybe quite an aggressive land-simplification was used when creating our
world.map to keep the file size down.

Thanks for spotting.

**Comment by devemux86** [comment]
> I cannot remember what real impact the land-simplification had here, but maybe quite an aggressive land-simplification was used when creating our world.map to keep the file size down.

AFAIK world.map does not need any pre-simplification before building to have good results.

Seeing various issues with split land polygons (in software & OpenGL rendering),
I'd avoid any such methods, leaving control to map-writer.
