### ISSUE TITLE
Map / POI creation verify

### ISSUE THREAD

**Issue by devemux86** [mapsforge/mapsforge-mapcreator#12]
Things can go wrong in server during map / poi build process, producing files with very small size.

From @ludwigb:
"one obvious improvement would be to only copy the new map files over the old ones, if the new ones are not much smaller than the ones being replaced".

**Comment by wish7code** [comment]
Guess we just need a 2 line check at https://github.com/mapsforge/mapsforge-mapcreator/blob/master/mapcreator.py#L250

(untested though!)

if not self.dry_run and PATH.exists(map_file_target_path) and PATH.getsize(map_file_target_path) > PATH.getsize(map_file_path):
    raise ProcessingException('new file %s is smaller than existing file %s, won't replace existing' % (map_file_path, map_file_target_path))

**Comment by devemux86** [comment]
Closed via 18aab9c986ec0e86d611769b8b5e47a1c544d0fe by @ludwigb.
