### ISSUE TITLE
Map creator new process

### ISSUE THREAD

**Issue by devemux86** [mapsforge/mapsforge-mapcreator#13]
We could change the map creation, in order to avoid continents extraction and speed up the process, e.g.:
- Download .pbf from [Geofabrik](http://download.geofabrik.de/)
- Follow the steps in our [Map creation (with coastlines)](https://github.com/mapsforge/mapsforge/blob/master/docs/MapCreation.md) guide

**Comment by applantation** [comment]
I think this would not only solve a lot of the problems on the server, but
would also be in line with my general philosophy that we should not
duplicate stuff that is already done somewhere else successfully.
The easier the better.
There might be some areas that are not served from geofabrik, but we never
promised that we would provide maps for all areas.

**Comment by devemux86** [comment]
See https://github.com/mapsforge/mapsforge-creator
