### ISSUE TITLE
Lake Constance issues/missing

### ISSUE THREAD

**Issue by boldtrn** [mapsforge/mapsforge-mapcreator#14]
When opening a map file created with the mapsforge-mapcreator of Germany (or Germany+Austria+Switzerland) the lake constance seems to be missing, probably since the lake is part of 3 countries the polygon is dropped as it's partly outside each boundary?

Attached is a screenshot with the [Kurviger App](https://play.google.com/store/apps/details?id=gr.talent.kurviger.pro) that uses VTM. Apparently the same behavior was reported for Mapsforge as well. The lake constance should be rendered where the attached screenshot has a "gray hole"

![screenshot_20170620-095154](https://user-images.githubusercontent.com/1553525/27529893-8a76fcfe-5a56-11e7-9d2c-b630dbeb619f.png)

**Comment by devemux86** [comment]
It depends on map-writer's input data and map creation method (as mentioned also in https://github.com/mapsforge/mapsforge/issues/967).
Map data are clipped to country `.poly` boundaries, except OpenStreetMapData land polygons which are clipped to map boundaries.
Map views are rectangular, but the content may be not, if have been cut with smaller (polygon) bounds.

**Comment by boldtrn** [comment]
Thanks for the fast reply. Shouldn't be "completeWays=yes and completeRelations=yes" the default approach for the mapsforge-mapcreator? WDYT?

**Comment by devemux86** [comment]
For that issue having the maps filling the whole rectangle could work, so that opening multiple ones would have most features. But maps are created with generic use in mind.
Or else we'd use (and other sites) the improved [zoom-interval-conf](https://github.com/mapsforge/mapsforge/blob/master/docs/Getting-Started-Map-Writer.md#known-pitfalls) a long time ago. :slightly_smiling_face:

**Comment by boldtrn** [comment]
> For that issue having the maps filling the whole rectangle could work, so that opening multiple ones would have most features. But maps are created with generic use in mind.

That's true, that's why I am asking about the completeWays and completeRelations :). This should be the default IMHO. For example [Geofabrik extracts also completeWays and completeRelations](http://download.geofabrik.de/technical.html).

**Comment by devemux86** [comment]
What happens if using [OpenAndroMaps](http://www.openandromaps.org/en/) maps with that lake?

**Comment by boldtrn** [comment]
I tried it with Baden Wuerttemberg. They include the lake, big parts of switzerland and also the vosges mountains. So they lake is rendered correctly.

**Comment by devemux86** [comment]
So they probably extract differently the data. @ludwigb ?

@boldtrn could you try with [AndroidMaps](http://www.androidmaps.co.uk/) too? They mention using Geofabrik.

**Comment by boldtrn** [comment]
> @boldtrn could you try with AndroidMaps too? They mention using Geofabrik.

It did not work with AndroidMaps. They mention: 

> Some maps we couldn't successfully generate are from download.mapsforge.org 

So I am not sure if this might be one of these maps?

**Comment by boldtrn** [comment]
Should I create a PR that adds the `completeWays` and the `completeRelations` to the Osmosis call?

**Comment by devemux86** [comment]
Need first to perform testing with a relevant map file.
Creating it without and with an option and see in client how it renders.

**Comment by boldtrn** [comment]
> Creating it without and with an option and see in client how it renders.

Yes sure :), but if we assume it would work, there is no reason not to do this, right?

**Comment by devemux86** [comment]
I tested the area with .pbf and .poly of [tuebingen-regbez](http://download.geofabrik.de/europe/germany/baden-wuerttemberg/tuebingen-regbez.html) from Geofabrik (so data are limited to .pbf but lake exists).

With default [--bounding-polygon](http://wiki.openstreetmap.org/wiki/Osmosis/Detailed_Usage_0.45#--bounding-polygon_.28--bp.29) lake is missing:
![1](https://user-images.githubusercontent.com/3484020/30446332-7fbd0194-9991-11e7-830b-f43b3742ede9.png)

With `--bounding-polygon completeWays=yes completeRelations=yes` lake is included:
![2](https://user-images.githubusercontent.com/3484020/30446341-852944da-9991-11e7-9bcd-4f1d0d622936.png)

@boldtrn do you want to post a PR with the needed changes?

BTW this behavior won't exist when have the new map creation process in #13.
