### ISSUE TITLE
Missing tunnels

### ISSUE THREAD

**Issue by devemux86** [mapsforge/mapsforge-mapcreator#7]
In our map creation process we use two external data sources (sea / land) which should follow the `layer` tag mechanism as all OSM data.

Currently only the sea rectangle has the `layer=-5` tag.
We need to add it also in land polygons, as now we have hidden elements, e.g. tunnels.

**Comment by devemux86** [comment]
With 0087e07c9e64f4e39ba68c1c44fa23596fac6a84 I added the `layer` tag in `shape2osm.py` script.

**Comment by ludwigb** [comment]
Installed it on our server and restarted map creation process.
